params:
  # 1. Pre-training
  latent_dim:  {choice: [8, 16, 32, 64]}
  enc_layers:  {choice: [1, 2, 3, 4]}
  enc_hidden:  {choice: [8, 16, 32, 64]}
  dec_layers:  {choice: [1, 2, 3, 4]}
  dec_hidden:  {choice: [8, 16, 32, 64]}
  dropout: {loguniform: [0.00000001, 0.5]}
  variational: {choice: [true, false]}
  alpha_REC: {loguniform: [0.00001, 1.0]}
  alpha_KLD: {loguniform: [0.00001, 1.0]}
  alpha_NLL: {loguniform: [0.00001, 1.0]}
  alpha_RANK: {loguniform: [0.00001, 1.0]}
  lr: {loguniform: [0.00001, 0.1]}  # Reduced upper bound 
  activation: {choice: ["relu", "leaky_relu", "gelu"]}
  weight_decay: {loguniform: [0.00000001, 0.1]}
  batch_size: {choice: [16, 32, 64, 128]}
  lr_scheduler: {choice: ["None", "cosine_annealing"]}
  interpolation: {choice: ["step", "linear"]}

  # 2. Clustering
  clustering_method: {choice: ["kmeans", "agglomerative", "GaussianMixture", "SpectralClustering"]}
  n_clusters: {int: [2, 8]} 

  # 3. Training
  num_durations: {int: [5, 15]}
  num_layers: {choice: [1, 2, 3, 4]}
  hidden_units: {choice: [8, 16, 32, 64]}
  alpha_DVC: {loguniform: [0.00001, 1.0]}
  alpha_IVCG: {loguniform: [0.00001, 1.0]}
  use_cluster_heads: {choice: [true, false]}

